theme: jekyll-theme-cayman
title: State Preferences for Political Agendas and Policy Position Proximity
description: A Computational Content Analysis Project on the United Nations General Debate Corpus